### ISSUE TITLE
hystrix-dashboard does not launch

### ISSUE THREAD

**Issue by wrichter** [redhat-helloworld-msa/helloworld-msa#12]
Image fabric8/hystrix-dashboard:1.0.17 does not launch on my OSE environment:

--- BEGIN CONTAINER LOG SNIPPET ---
Checking *.war in /maven
Linking /maven/ROOT.war --> /opt/jetty/webapps/ROOT.war
ln: failed to create symbolic link '/opt/jetty/webapps/ROOT.war': Permission denied
Running Jetty: 
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://10.1.2.8:8778/jolokia/
2016-09-19 18:59:24.547:INFO:ifasjoejs.Server:jetty-8.y.z-SNAPSHOT
2016-09-19 18:59:24.578:INFO:ifasjoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779
2016-09-19 18:59:24.851:INFO::main: Logging initialized @567ms
2016-09-19 18:59:24.911:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2016-09-19 18:59:25.045:WARN:oejuc.FileNoticeLifeCycleListener:main: 
java.io.FileNotFoundException: /opt/jetty/jetty.state (Permission denied)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
[...]
--- END CONTAINER LOG SNIPPET ---

I can see that the permission of the target directory does not have write permissions on the jetty directory: 

[root@ose3-master1 ~]# oc rsh hystrix-dashboard-tv4vk
sh-4.2$ ls -alsn /maven
total 1576
   0 drwxr-xr-x.  2 0 0      21 May 11 09:19 .
   4 drwxr-xr-x. 19 0 0    4096 Sep 19 18:59 ..
1572 -rw-r--r--.  1 0 0 1606587 May 11 09:19 ROOT.war
sh-4.2$ ls -asln /opt/jetty/webapps/
total 8
0 drwxr-xr-x.  2 501 20   23 Oct 21  2015 .
4 drwxr-xr-x. 10 501 20 4096 Jul 30  2015 ..
4 -rw-r--r--.  1 501 20 1412 Jul 30  2015 README.TXT
sh-4.2$ id
uid=1000080000 gid=0(root) groups=1000080000
sh-4.2$

**Comment by wrichter** [comment]
solved the problem by assigning the anyuid scc to the ribbon user:
$ oc project helloworld-msa
$ oadm policy add-scc-to-user anyuid -z ribbon
